### ISSUE TITLE
Hello, I have the following problem when running the code, what is the reason?

### ISSUE THREAD

**Issue by ykingliu** [RetroCirce/HTS-Audio-Transformer#13]
RuntimeError: upsample_bicubic2d_backward_out_cuda does not have a deterministic implementation, but you set 'torch.use_deterministic_algorithms(True)'.
 You can turn off determinism just for this operation, or you can use the 'warn_only=True' option, if that's acceptable for your application. 
 You can also file an issue at https://github.com/pytorch/pytorch/issues to help us prioritize adding deterministic support for this operation

**Comment by RetroCirce** [comment]
In the main.py search 'deterministic', and set it to be True (inside the trainer instance)
I think this is because the latest version of PyTorch and PyTorch lightening make it underteministic.

Best,
Ke

**Comment by ykingliu** [comment]
Thank you for your &nbsp;reply. Which version of pytorch do you use?




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "RetroCirce/HTS-Audio-Transformer"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年7月27日(星期三) 上午8:33
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [RetroCirce/HTS-Audio-Transformer] Hello, I have the following problem when running the code, what is the reason? (Issue #13)





 
In the main.py search 'deterministic', and set it to be True (inside the trainer instance)
 I think this is because the latest version of PyTorch and PyTorch lightening make it underteministic.
 
Best,
 Ke

**Comment by RetroCirce** [comment]
At that time I think it is 1.10.2. But it doesn't matter, because even you just set the deterministic to be False (sorry it should be False not True as above), the model can work as the same.

**Comment by ykingliu** [comment]
Thank you for your help. I have solved the problem and successfully reproduced your results. I wish you a happy life




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "RetroCirce/HTS-Audio-Transformer"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年7月27日(星期三) 上午9:32
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [RetroCirce/HTS-Audio-Transformer] Hello, I have the following problem when running the code, what is the reason? (Issue #13)





 
When training the ESC-50 dataset, you need to use the pertained audioset model, instead of the the pretrain imagine model.
 This follows the previous settings from benchmark.
 Check this issue (while this is in Chinese):
 #6
 
Also check this, my new-writing esc-50 training tutorial It should help you out.
