### ISSUE TITLE
预训练的.ckpt文件

### ISSUE THREAD

**Issue by dong-0412** [RetroCirce/HTS-Audio-Transformer#17]
你好，我看见在htsat_esc_training.ipynb文件中的数据准备部分，下载完ESC-50的文件后有要求下载一个名为htsat_audioset_pretrain.ckpt的文件，但是我试了并无法下载，1OK8a5XuMVLyeVKF117L8pfxeZYdfSDZv这是对应的ID，我想知道怎么在不适用gdown的情况下下载这个文件

**Comment by RetroCirce** [comment]
你好！因为这个文件太大了，所以只能用gdown..
如果你不想用gdown，我之前有试过这种，但是这个方法能不能适用已经不知道了：https://medium.com/@skylarng89/download-large-files-from-google-drive-using-drive-api-fcbdba64fb18
