### ISSUE TITLE
关于音频事件检测 

### ISSUE THREAD

**Issue by dong-0412** [RetroCirce/HTS-Audio-Transformer#19]
你好，
  我想知道用于音频事件检测的部分，也就是关于定位的部分（在DESED数据上跑到模型），和那种在esc-50这种数据集上跑到分类任务相比，多了那些操作，可以大体说说吗。
  论文中说是那个最后的Token Semantic Module实现了定位的功能，我是初学者只看到有卷积操作在里模块里面，可以粗略讲讲关于实现定位的细节吗。

**Comment by RetroCirce** [comment]
token semantic module 本质上就是一个CNN将频率轴进行了压缩，然后把channel的维度转换为了类别的维度，因为在[这篇paper](https://openaccess.thecvf.com/content/ICCV2021/papers/Gao_TS-CAM_Token_Semantic_Coupled_Attention_Map_for_Weakly_Supervised_Object_ICCV_2021_paper.pdf)中它将其作为token semantic moduel称呼，我们也在我们的paper中用了这个说法；更进一步说，token semantic module还有一个attention的平均机制，你可能在我代码中的注释中有所看到，但是我们发现最后的效果比较类似，于是就没有使用。

关于定位的部分，你可以看到我们的model最后会输出一个527维的向量（对应audioset中的527）类，这个向量其实上是由上一层的(T，527)矩阵平均过来的，如果你只有弱标签，你就只能通过这个向量去做loss计算（因为你没有每一个时刻上的数据），如果你有强标签，你就不仅可以527维的向量去做loss计算，还可以加上用你强标签的数据转换成（T,527）的矩阵答案，和model的这个矩阵做loss。

如此一来，就可以用该model跑定位模型了

**Comment by dong-0412** [comment]
感谢你的回复，
  我又回过头看了关于token semantic module 部分的代码，仍然有一些不明白的地方要请教你，
            
            B, N, C = x.shape
            SF = frames_num // (2 ** (len(self.depths) - 1)) // self.patch_stride[0]
            ST = frames_num // (2 ** (len(self.depths) - 1)) // self.patch_stride[1]
            x = x.permute(0,2,1).contiguous().reshape(B, C, SF, ST)        
            B, C, F, T = x.shape

            # group 2D CNN
            c_freq_bin = F // self.freq_ratio
            x = x.reshape(B, C, F // c_freq_bin, c_freq_bin, T)
            x = x.permute(0,1,3,2,4).contiguous().reshape(B, C, c_freq_bin, -1)

            x = self.tscam_conv(x)
            x = torch.flatten(x, 2) # B, C, T
1.group 2D 那里，前面已经将特征图分成了SF,ST 的形式了，这里的关于特征图的形状的变换的作用是什么？

2.self.tscam_conv处理后的特征图的形状变成了B,Class,T'，那么这个T'是有什么物理意义在里面吗？

3.上述操作完成了我看到程序中对x进行上采样来生成fpx作为framewise_output，并用它来做定位（确定开始结束时间？），那么这个fpx为什么来用来做定位，以及fpx（B，1024，527）的1024的物理意义是什么？

  希望您能抽空解决我的疑惑

**Comment by wengstA** [comment]
您好，我想请问一下token semantic module是否有在强标签的数据集上做训练呢？如果有的话是在desed的train数据集上做训练吗？我似乎没有看到这部分的代码？想知道你们是怎么训练token semantic module的

**Comment by chumingqian** [comment]
Hello， @RetroCirce :
        May I ask about the sound event detection task, for the DESED dataset, did you just use the test set for testing, and did not use the dataset for training?

**Comment by jonwomack** [comment]
@chumingqian 
DESED dataset is only used for testing. 
[During training](https://github.com/RetroCirce/HTS-Audio-Transformer/blob/723174908cb7bec95aead8e704f33035e0a66474/main.py#L256-L265), DESED is not a supported dataset type.
[During evaluation](https://github.com/RetroCirce/HTS-Audio-Transformer/blob/723174908cb7bec95aead8e704f33035e0a66474/fl_evaluate.py#L77), the inference results produced from the AudioSet model (527 classes) are [mapped](https://github.com/RetroCirce/HTS-Audio-Transformer/blob/723174908cb7bec95aead8e704f33035e0a66474/config.py#L116-L128) to the 10 DESED classes.
