### ISSUE TITLE
How can I  test model？

### ISSUE THREAD

**Issue by yyssxxx** [RetroCirce/HTS-Audio-Transformer#26]
Hello , in "htsat_esc_training.ipnb", how can i find test_data? Or i should design the test_data myself? I'm not familiar with pytorch-lightning.

**Comment by RetroCirce** [comment]
Hi, please follow the readme or the comments in the ipynb file, there is a link for downing the dataset.

**Comment by yyssxxx** [comment]
> Hi, please follow the readme or the comments in the ipynb file, there is a link for downing the dataset.

Thanks for answering, but i mean how can i use the data from the test_data the get the accuracy in the test data , i think "./workspace/esc-50/raw/ESC-50-master/audio/1-7456-A-13.wav" maybe is not in the test_data? I dont know "pytorch_lightning" too much, i want to find the test data.
