### ISSUE TITLE
How can run this project with one GPU?!

### ISSUE THREAD

**Issue by saeedmaroof** [RetroCirce/HTS-Audio-Transformer#32]
hi.
I am trying to test this model on Google Speech Command but after testing progress bar complete, I get this error:
`Default process group has not been initialized, please make sure to call init_process_group`

I google this error and found that this error happens because of 'SyncBatchNorm' in 1 GPU and I should replace them by normal ones.
in your code i found 'sync_batchnorm' parameter in pl.Trainer() and set its value to 'False' and run test command again but it wasn't work.

could anyone please tell me how can i run this project on 1 GPU ?!
thanks.

**Comment by JonathanFL** [comment]
Might be related to [#21](url)

**Comment by RetroCirce** [comment]
Hi, 

Sorry for the late reply, I was extremely busy these days for different dues. Yes, you can refer to #21 .
Also, you don't need to change the sync_batchnorm, just remain it True, it will automatically turn to false if it is not run on multi-gpu.
