### ISSUE TITLE
Model Checkpoints

### ISSUE THREAD

**Issue by wonyangcho** [RetroCirce/HTS-Audio-Transformer#42]
Hello. I am a student studying various audio transformer papers, and I am impressed by your work. I have a few questions.

- In the model checkpoints you provide, the filenames for audioset range from 1 to 6. What does it signify?
- How were the models in the 'other settings' folder trained?

Thank you.

**Comment by wonyangcho** [comment]
I found the answer in the config.py file. Thank you.

**Comment by Sreyan88** [comment]
Hi @wonyangcho , can you please share the answer in the config.py file. Would be grateful!

**Comment by wonyangcho** [comment]
@Sreyan88 

I referred to the following part.

# trained from a checkpoint, or evaluate a single model
resume_checkpoint = None
# "/home/Research/model_backup/AudioSet/HTSAT_AudioSet_Saved_1.ckpt"

esm_model_pathes = [
    "/home/Research/model_backup/AudioSet/HTSAT_AudioSet_Saved_1.ckpt",
    "/home/Research/model_backup/AudioSet/HTSAT_AudioSet_Saved_2.ckpt",
    "/home/Research/model_backup/AudioSet/HTSAT_AudioSet_Saved_3.ckpt",
    "/home/Research/model_backup/AudioSet/HTSAT_AudioSet_Saved_4.ckpt",
    "/home/Research/model_backup/AudioSet/HTSAT_AudioSet_Saved_5.ckpt",
    "/home/Research/model_backup/AudioSet/HTSAT_AudioSet_Saved_6.ckpt"
]
This part seems to use 6 models in an ensemble.

Therefore, I judged that any model can be used as a pre-trained model without any problem."

Best regards.

**Comment by Sreyan88** [comment]
Do you have any idea what the other folder experiments are pointing to? Thank You!

**Comment by RetroCirce** [comment]
The default checkpoint is in AudioSet folder. There are six available checkpoints and either of them can have a similar map reported in the paper (around 0.465-0.473). 

The checkpoints in ESC and SCV2 folders are the fine-tuned checkpoints on ESC-50 and SCV2 datasets. The reported performance is on the paper.

The other setting folder shows some checkpoints we added later or before. Such as using/without using the imagenet checkpoint when training on Audioset. Or the model training on different sampling rate (such as 48000hz). You can try for that if you found them helpful. They actually also got very good performance.
