### ISSUE TITLE
Usage on Strongly labelled Dataset for SED

### ISSUE THREAD

**Issue by urvashi07** [RetroCirce/HTS-Audio-Transformer#45]
Hi, 

Thank you for your code and the great work!

I had a question regarding usage of strongly labelled data for the task of sound event detection. How can I do the inference/prediction to get the time stamps of the sound events along with the classes?

Thanks in advance!

**Comment by RetroCirce** [comment]
Hi, you can refer [this](https://github.com/RetroCirce/HTS-Audio-Transformer/issues/25)

**Comment by urvashi07** [comment]
Thank you, I will try it out
