### ISSUE TITLE
RuntimeError: Default process group has not been initialized, please make sure to call init_process_group.

### ISSUE THREAD

**Issue by LiupengNew** [RetroCirce/HTS-Audio-Transformer#59]
Environment setup: wsl2 + Ubuntu 20.04 + PyTorch 1.12.0 + single GPU
After running "python main.py train" with the ESC-50 dataset, I encountered an error when running "python main.py test":
RuntimeError: Default process group has not been initialized, please make sure to call init_process_group.
Help! Has anyone encountered this issue before? Any solutions?

**Comment by wthu12138** [comment]
Hi,
I have the same problem. I wonder how to solve it. Thank u!
