### ISSUE TITLE
关于精度没有达到论文中的水平的问题

### ISSUE THREAD

**Issue by JasYY6** [RetroCirce/HTS-Audio-Transformer#6]
![image](https://user-images.githubusercontent.com/60248596/177768756-1d62333c-aa28-422f-9a5d-796cc185dbb1.png)
关于您的模型，已按照您的配置执行，采用的是esc50数据集，并加载了swin_transformer的预训练模型，但最后的精度如图，只能达到0.88，测试也是如此，不知哪里出了问题，您可以给一些建议吗？十分感谢！

**Comment by RetroCirce** [comment]
您好，训练esc-50的时候需要将esc-50里的数据重采样为32000，因为我们训练audioset的时候是32000的采样率；同时预训练模型是先训练在audioset的，不仅仅是swin-transformer在imagenet上的预训练模型。

谢谢！

**Comment by JasYY6** [comment]
您好，我不太理解您说的先在audioset上预训练的意思，是先把swin_transformer的参数迁移过来，然后再在audioset上训练，最后在esc-50上测试可以到0.97的精度吗？还是其他意思呢？
刚接触深度学习，如有打扰还请见谅。
谢谢！

**Comment by JasYY6** [comment]
您好，感谢您的指点，我已经成功复现了您的结果，祝您生活愉快！

**Comment by RetroCirce** [comment]
是的，在audioset上预训练，不客气！
